# This is a basic workflow to help you get started with Actions

name: ReactJs boilerplate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main] #branch changed from master to main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Node.Js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14 #version changed from 12 to 14
      - name: Install dependencies of the application
        run: npm install
      - name: Prepare for Yarn Installation
        uses: borales/actions-yarn@v2.3.0
        with:
          # Yarn installation command
          cmd: install
      - name: Build app
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build bootcamp2020-class2-bizztechs.surge.sh --token ${{secrets.SURGE_TOKEN}}
