name: Deployment to surge suing Github actions

on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    name: Deployment to surge  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install node version 12
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      # Install npm packages
      - name: Install packages
        run: npm install

      # Build react app
      - name: Build the app
        run: npm run build

      # Install Surge 
      - name: Install Surge
        run: npm install -g surge

      # Deploy to the defined URL using the token
      - name: Deploy to surge
        run: surge ./build bootcamp2020-class2-bizztechs.surge.sh --token ${{secrets.SURGE_TOKEN}}
